services:
  ros2-dev:
    # Build the image from the Dockerfile in the current directory.
    build:
      context: .
      dockerfile: Dockerfile
      # Pass host user/group IDs to the build process to avoid file permission issues.
      args:
        USER_ID: ${UID:-1013}
        GROUP_ID: ${GID:-1013}
    # This explicitly names the image that is created from the final stage.
    image: my_user/ros2_autonomous_pathfinder:latest